config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'materials', to: 'materials#index'
  get 'materials/:id', to: 'materials#show'
  get 'materials/new', to: 'materials#new'
  post 'materials', to: 'materials#create'
  get 'materials/:id', to: 'materials#edit'
  patch 'materials/:id', to: 'materials#update'
  delete 'materials/:id', to: 'materials#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/material.rb
class Material < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
    @materials = Material.all
  end

  # def show
  #   @material = Material.find(params[:id])
  # end

  def edit
    @material = Material.find(params[:id])
  end

  def new
    @material = Material.new
  end

  def create
    @material = Material.new(material_params)
    @material.user = current_user

    if @material.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @material = Material.find(params[:id])
    @material.update(material_params)

    redirect_to material_path(@material)

  end

  def destroy
    @material = Material.find(params[:id])
    @material.destroy

    redirect_to root_path
  end

  private

  def material_params
    params.require(:material).permit(:name, :qtde)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Produto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/materials/edit.html.erb
<div class="container">
  <h1>edit a form</h1>
  <%= simple_form_for(@material) do |f|%>
    <%= f.input :name%>
    <%= f.input :qtde%>
    <%= f.submit "Submit", class: "btn btn-success" %>
  <%end %>
</div>

app/views/materials/index.html.erb
<p>Pagina index</p>
<% @materials.each do |material|%>
<li><%= material.name%></li>
<li><%= "#{material.qtde} un"%></li>

<% end%>

app/views/materials/new.html.erb
<div class="form-row align-items-center">
  <div class="container mt-5">
    <h1 class = "text-center"> Add material </h1>


    <%= simple_form_for(@material) do |f|%>
      <%= f.input :name%>
      <%= f.input :qtde%>


      <%= f.submit "Submit", class: "btn btn-success" %>
    <%end %>
  </div></div>
</div>

app/views/materials/show.html.erb
<div>
<div class='container'>
    <div class='title'>
      <h1><%= @material.name %></h1>
    </div>

    <div class="row">

      <div class="text-center col-sm-4 mt-5">
        <div class='container'>
          <div id="price-discount">
            <h5 class="text-left">Quantidade: <%= @material.qtde%>un</h5>
          </div>
        </div>
      </div>
      <div id="coupon-buttons">
        <%= link_to "Edit", edit_material_path(@material)%>
        <%= link_to "Delete", (@material), method: :delete, data: { confirm: "Are you sure?" } %>
     </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>

<%= link_to "Index", materials_path%>
<%= link_to "Create", materials_new_path%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>